# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
