# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160916_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='active',
        ),
    ]
