# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_album_published_field_to_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(null=True, related_name='photos', to='imager_images.Photo'),
        ),
    ]
